version: "3.9"
   
services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:${PORT:-8000}
    volumes:
      - .:/app
    ports:
      - ${PORT:-8000}:${PORT:-8000}
    environment:
      SECRET_KEY: ${SECRET_KEY:-queenladygaga}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-["*"]}
      DEBUG: ${DEBUG:-true}
      PORT: ${PORT:-8000}
      DB_ENGINE: ${DB_ENGINE:-django.db.backends.postgresql}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-sadian_db}
      DB_USER: ${DB_USER:-sadian}
      DB_PASSWORD: ${DB_PASSWORD:-sadian}
      DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL:-sadiandenniel@gmail.com}
      EMAIL_HOST: ${EMAIL_HOST:-mail}
      EMAIL_PORT: ${EMAIL_PORT:-1025}
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - sadian_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME:-sadian_db}
      POSTGRES_USER: ${DB_USER:-sadian}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-sadian}
  
  mail:
    image: mailhog/mailhog
    ports:
      - 8025:8025

volumes:
  sadian_db:
