# Generated by Django 2.2 on 2019-07-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
