# Generated by Django 2.1.4 on 2019-01-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20190106_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinecontent',
            name='side',
            field=models.CharField(default='left', max_length=10),
            preserve_default=False,
        ),
    ]
