# Generated by Django 2.1.4 on 2019-03-17 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_timeline_left'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timeline',
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
