# Generated by Django 2.1.4 on 2019-03-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_auto_20190317_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True)),
                ('desc', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateField(),
        ),
    ]
