# Generated by Django 2.1.4 on 2019-03-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_auto_20190317_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='left',
            field=models.BooleanField(default=True),
        ),
    ]
