# Generated by Django 2.2 on 2019-07-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('day', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('quote', models.TextField()),
                ('whose', models.CharField(max_length=255)),
            ],
        ),
    ]
